# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='avatar',
            field=models.ImageField(null=True, upload_to='mas/static/images/'),
        ),
    ]
