# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mas', '0002_auto_20180307_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='mas/static/images/'),
        ),
    ]
