# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mas', '0003_auto_20180307_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
            ],
        ),
    ]
