# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mas', '0007_symptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='avatar',
            field=models.ImageField(blank=True, default='mas/static/images/download.jpg', null=True, upload_to='mas/static/images/'),
        ),
    ]
