# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-04 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mas', '0008_auto_20180404_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.URLField(default='', max_length=128),
        ),
    ]
